---
title: "Numerical Optimization"
subtitle: "<html><div style='float:left'></div><hr color='#459DE0' size=5px width=1100px></html>"
author: Ivan Rudik
date: AEM 7130
output:
  xaringan::moon_reader:
    css: [default, metropolis, metropolis-fonts] 
    lib_dir: libs
    nature:
      highlightStyle: bash
      highlightLines: true
      countIncrementalSlides: false
      ratio: '16:9'

---

# Software and stuff

Necessary things to do:

- Install the QuantEcon Julia package
- Install the Optim or NLOpt Julia packages

---

# Optimization

All econ problems are optimization problems

--

- Max profits

--

- Min costs

--

- Max PV E[welfare]

--

Some are harder than others:

--

- Individual utility max: easy

--

- Decentralized electricity market with nodal pricing: hard

--

- One input profit maximization problem: easy

--

- N-input profit maximization with learning and forecasts: hard

---

# Things we will do

1. Linear rootfinding
2. Non-linear rootfinding
3. Complementarity problems
4. Non-linear unconstrained maximization/minimization
5. Non-linear constrained maximization/minimization
---

# Linear rootfinding

How do we solve these?

--

Consider a simple generic problem:

$Ax = b$

--

Invert $A$

$x = A^{-1}b$

--

The end

---

# Non-linear rootfinding

With non-linear rootfinding problems we want to solve:

$f(x) = 0, f:\mathbb{R}\rightarrow\mathbb{R}^n$

--

What's a common rootfinding problem?

--

Can we reframe a common economic problem as rootfinding?

--

Yes!

--

Fixed point problems are rootfinding problems:

--

$g(x) = x \Rightarrow f(x) \equiv g(x) - x = 0$
